name: rentify_all
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
 
  firebase_database: ^8.0.0
  carousel_pro: ^1.0.0
  firebase_auth: ^3.1.2
  cloud_firestore: ^2.5.3
  google_sign_in: ^5.1.1
  shared_preferences: ^2.0.8
  fluttertoast: ^8.0.8
  provider: ^6.0.1
  custom_page_route: ^0.0.3
  firebase_core: ^1.7.0
  cached_network_image: ^3.1.0
  intl : ^0.17.0
  flutter_spinkit: ^5.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+2
  #firebase_messaging: ^11.1.0
  #http: ^0.13.4
  telephony: ^0.1.4
  flutter_datetime_picker: ^1.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/splash_image/image.png
    - images/splash_image/back.jpg
  #cars
    - images/cars/car1.jpg
    - images/cars/car2.jpg
    - images/cars/car3.jpg
    - images/cars/celerio.png
    - images/cars/Tiagotata.png
    - images/cars/carlogo.jpg

    - images/cars/rent_cars/ZAudi A5.png
    - images/cars/rent_cars/Zaudi-car.png
    - images/cars/rent_cars/Zbmw-320i.png
    - images/cars/rent_cars/ZHonda Civic.png
    - images/cars/rent_cars/ZHonda-accord exl.png
    - images/cars/rent_cars/ZHyundai Santa Fe Sport.png
    - images/cars/rent_cars/ZHyundai-Venue.png
    - images/cars/rent_cars/ZHyundai Tucson 2020.png

    - images/cars/rent_cars/Zkia sorento Lx.png
    - images/cars/rent_cars/Zmahendra-verito-toreador.png
    - images/cars/rent_cars/Zred_hundai.png
    - images/cars/rent_cars/ZSilver Hyundai Kona.png




#bikes
    - images/cars/bikes/bike1.jpg
    - images/cars/bikes/bike2.jpg
    - images/cars/bikes/bike3.jpg
    - images/cars/bikes/bikeLogo.jpg


    - images/cars/bikes/cycle.jpg
    - images/cars/carLogo2.jpg
  
    - images/cars/rent_cars/bmwx1.jpeg
    #bikes
    - images/rent_bikes/hondasp125.jpg
    - images/rent_bikes/pulsar200ns.png
    - images/rent_bikes/hondahornet.png
    - images/rent_bikes/hero.png
    - images/rent_bikes/bullet.png 
    - images/rent_bikes/hero.png    
    - images/rent_bikes/hondacd110.png
    - images/rent_bikes/bikelogo.jpg

    #buses
    - images/buses/buslogo.png
    - images/buses/bluebus.png
    - images/buses/orange_bus.png
    - images/buses/blue primium.png

    #commercial
    - images/commercial/tatamagic.png
    - images/commercial/tatamagicmotor.png
    - images/commercial/tatasuperace.png
    - images/commercial/commerciallogo.png

    - images/rent_cycle/herolectro.jpg
    - images/cars/rent_cars/hondajazz.jpeg
    - images/cars/rent_cars/hondahrv.jpg
    - images/cars/rent_cars/volvos60.jpeg
    - images/cars/rent_cars/bmwx1.jpeg
    - images/google.jpg
    - images/gl.png
    - images/fl.png
    - images/letsgo.png
    - images/backgroud.jpeg

    - images/companylogo/hyundai.png
    - images/companylogo/hondalogo.png
    - images/companylogo/ford.png
    - images/companylogo/ford1.png
    - images/companylogo/toyatologo.png
    - images/companylogo/Nissan.png
    - images/companylogo/Suzuki.png
    - images/companylogo/BMW.png
#icon
    - images/icon/admin.png
    - images/icon/driver.png
    - images/icon/login.png

#developer
    - images/developer/nakul.jpg    
    - images/developer/sahil.jpg  
    - images/developer/jayesh.jpg
    - images/developer/logo.png
    - images/developer/shivani.jpg
    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ephesis
      fonts:
        - asset: fonts/Ephesis-Regular.ttf
       
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
